-- +goose up 
CREATE TABLE feeds (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    name TEXT NOT NULL, 
    url TEXT NOT NULL UNIQUE,
    user_id  UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE 
);

-- +goose down 
DROP TABLE feeds;
